#!/bin/bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/dns"
export OP_SERVICE_ACCOUNT_TOKEN="$(cat ../OP_SERVICE_ACCOUNT_TOKEN)"
op run --env-file=.env -- docker run --rm \
  -e CLOUDFLARE_API_TOKEN \
  -e UNIFI_API_KEY \
  -v "$(pwd):/dns" \
  ghcr.io/stackexchange/dnscontrol preview
