#!/bin/bash
source $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/../before_run

docker run \
  --log-driver=splunk \
  --log-opt splunk-url=$HUMIO_URL \
  --log-opt splunk-token=$HUMIO_INGEST_TOKEN \
  --detach \
  --name cloudflare-ddns \
  --restart=unless-stopped \
  -e API_KEY=$CLOUDFLARE_API_KEY \
  --tty \
  cloudflare-ddns