services:
  rathole-server:
    container_name: numbat-rathole-server
    build:
      context: ..
      args:
        STACK_CONTENT_HASH: ${BUILD_HASH_RATHOLE_SERVER:-unset}
    image: numbat-rathole:local
    pull_policy: never
    restart: unless-stopped
    network_mode: host
    security_opt:
      - label:disable
      - no-new-privileges:true
    environment:
      RATHOLE_CONFIG_TEMPLATE: /etc/rathole/server.toml.tmpl
      RATHOLE_NOISE_LOCAL_PRIVATE_KEY: ${RATHOLE_NOISE_LOCAL_PRIVATE_KEY}
      RATHOLE_PUBLIC_TLS_TOKEN: ${RATHOLE_PUBLIC_TLS_TOKEN}
      RATHOLE_FORGEJO_SSH_TOKEN: ${RATHOLE_FORGEJO_SSH_TOKEN}
      RATHOLE_PROTECTED_HTTP_TOKEN: ${RATHOLE_PROTECTED_HTTP_TOKEN}
      RATHOLE_BILBY_SSH_TOKEN: ${RATHOLE_BILBY_SSH_TOKEN}
      RATHOLE_VOLTAIRE_SSH_TOKEN: ${RATHOLE_VOLTAIRE_SSH_TOKEN}
      RATHOLE_KANGAROO_SSH_TOKEN: ${RATHOLE_KANGAROO_SSH_TOKEN}
      RATHOLE_FRACTAL_SSH_TOKEN: ${RATHOLE_FRACTAL_SSH_TOKEN}
      RATHOLE_FRACTAL_HTTP_TOKEN: ${RATHOLE_FRACTAL_HTTP_TOKEN}
      RATHOLE_VOLTAIRE_HTTP_TOKEN: ${RATHOLE_VOLTAIRE_HTTP_TOKEN}
      RATHOLE_PINELAKE_SSH_TOKEN: ${RATHOLE_PINELAKE_SSH_TOKEN}
      RATHOLE_PINELAKE_HTTP_TOKEN: ${RATHOLE_PINELAKE_HTTP_TOKEN}
      RATHOLE_PINELAKE_PLEX_TOKEN: ${RATHOLE_PINELAKE_PLEX_TOKEN}
    volumes:
      - ${NUMBAT_REPO_PATH:-/opt/komodo-periphery/etc-komodo/repos/podhaus-numbat}/relay/numbat:/etc/rathole:ro
    labels:
      podhaus.stack-content-hash: ${STACK_CONTENT_HASH:-unset}
