#!/bin/bash
docker pull python
source $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/../before_run
sudo docker build --build-arg cloudflare_api_token=${CLOUDFLARE_API_TOKEN} --build-arg admin_email=${ADMIN_EMAIL} -t certbot .