#!/bin/bash
source $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/../before_run

sudo docker run \
  --log-driver=splunk \
  --log-opt splunk-url=$HUMIO_URL \
  --log-opt splunk-token=$HUMIO_INGEST_TOKEN \
  --detach \
  --name certbot \
  --restart=unless-stopped \
  --mount="type=volume,source=letsencrypt,destination=/etc/letsencrypt" \
  --tty \
  certbot

