#!/bin/bash
source $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/../before_run

sudo docker run \
  --detach \
  --name kibana \
  --net dockernet \
  --link elastic:elasticsearch \
  -p 5601:5601 \
  kibana