#!/bin/bash
source $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/../before_run

sudo docker run \
  --detach \
  --name kibana \
  --net dockernet \
  --restart=unless-stopped \
  --link elasticsearch:elasticsearch \
  --log-driver=elastic/elastic-logging-plugin:7.11.1 \
  --log-opt hosts="http://localhost:9200" \
  --log-opt index="dockerlogs-%{+yyyy.MM}" \
  -p 5601:5601 \
  kibana