services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Australia/Perth
      PLEX_UID: "1000"
      PLEX_GID: "100"
      CHANGE_CONFIG_DIR_OWNERSHIP: "false"
    volumes:
      - /Users/Shared/Jump/plex:/config
      - /Users/Shared/Pouch:/Users/Shared/Pouch
    tmpfs:
      - /transcode:size=4g
