#!/usr/bin/env bash
# bilby host sshd: trust the Cloudflare Access SSH CA so the
# browser-rendered terminal at https://ssh.pod.haus can log in with a
# short-lived certificate (principal = email prefix `nathan`, matching
# the unix account). It also installs Sky's public key for native SSH as
# the nathan account through the same Cloudflare Access tunnel. Password
# auth is left enabled as a fallback.
#
# The CA public key is generated by Terraform
# (cloudflare_zero_trust_access_short_lived_certificate.bilby_ssh) and
# checked in as cloudflare_ca.pub next to this script. It is a PUBLIC
# key — safe in git. Re-run idempotently after `terraform apply` if the
# CA is ever rotated (re-capture via `terraform output -raw
# ssh_ca_public_key > cloudflare_ca.pub`).
#
# Run: sudo ./bilby/host-sshd/install.sh
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CA_SRC="$HERE/cloudflare_ca.pub"
CA_DST="/etc/ssh/cloudflare_ca.pub"
SKY_KEY_SRC="$HERE/sky_access.pub"
NATHAN_HOME="/home/nathan"
AUTHORIZED_KEYS="$NATHAN_HOME/.ssh/authorized_keys"
SSHD_CONFIG="/etc/ssh/sshd_config"
MARKER="# --- podhaus: Cloudflare Access browser-SSH CA (ssh.pod.haus) ---"

[ "$(id -u)" -eq 0 ] || { echo "must run as root (sudo)"; exit 1; }
[ -f "$CA_SRC" ] || { echo "missing $CA_SRC — run terraform apply first"; exit 1; }
[ -f "$SKY_KEY_SRC" ] || { echo "missing $SKY_KEY_SRC"; exit 1; }
ssh-keygen -l -f "$CA_SRC" >/dev/null || { echo "invalid CA pubkey"; exit 1; }
ssh-keygen -l -f "$SKY_KEY_SRC" >/dev/null || { echo "invalid Sky pubkey"; exit 1; }

install -o root -g root -m 0644 "$CA_SRC" "$CA_DST"
echo "installed $CA_DST"

if ! grep -qF "$MARKER" "$SSHD_CONFIG"; then
  {
    echo ""
    echo "$MARKER"
    echo "TrustedUserCAKeys $CA_DST"
  } >> "$SSHD_CONFIG"
  echo "appended TrustedUserCAKeys block to $SSHD_CONFIG"
else
  echo "TrustedUserCAKeys block already present"
fi

install -d -o nathan -g nathan -m 0700 "$NATHAN_HOME/.ssh"
touch "$AUTHORIZED_KEYS"
chown nathan:nathan "$AUTHORIZED_KEYS"
chmod 0600 "$AUTHORIZED_KEYS"
if ! grep -qxFf "$SKY_KEY_SRC" "$AUTHORIZED_KEYS"; then
  printf '%s\n' "$(<"$SKY_KEY_SRC")" >> "$AUTHORIZED_KEYS"
  echo "installed Sky's public key for nathan"
else
  echo "Sky's public key already installed"
fi

sshd -t
echo "sshd config valid"
systemctl reload sshd
echo "sshd reloaded — ssh.pod.haus accepts CF certificates and provisioned keys"
