[[stack]]
name = "fractal-ofelia"
description = "Label-based scheduler for container jobs on fractal"
tags = ["fractal", "podhaus"]

[stack.config]
server = "fractal"
linked_repo = "podhaus-fractal"
run_directory = "ofelia/fractal"
environment = """
TZ=[[TZ]]
"""
