#!/bin/bash
source $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/../before_run

sudo docker run \
  --log-driver=splunk \
  --log-opt splunk-url=$HUMIO_URL \
  --log-opt splunk-token=$HUMIO_INGEST_TOKEN \
  --detach \
  --mount="type=volume,source=reviewer,destination=/app/db" \
  --name reviewer \
  --network=host \
  --restart=unless-stopped \
  --net=host \
  --restart=unless-stopped \
  reviewer