[[stack]]
name = "home-assistant"
description = "Home Assistant home automation"
tags = ["podhaus"]

[stack.config]
server = "podhaus"
files_on_host = true
run_directory = "/etc/komodo/repo/home-assistant"

environment = """
TZ=[[TZ]]
PODHAUS_REPO=[[PODHAUS_REPO]]
"""
