#!/bin/bash
source $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/../before_run

sudo docker run \
  --detach \
  --name elasticsearch \
  --net dockernet \
  -p 9200:9200 \
  -p 9300:9300 \
  -e "discovery.type=single-node" \
  --mount="type=volume,source=elasticsearch,destination=/usr/share/elasticsearch/data" \
  elasticsearch