services:
  pinelake-ofelia:
    container_name: pinelake-ofelia
    image: mcuadros/ofelia:0.4.0-beta.5
    restart: unless-stopped
    command: daemon --docker
    environment:
      TZ: ${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      podhaus.stack-content-hash: ${STACK_CONTENT_HASH:-unset}
