#!/bin/bash
source $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/../before_run

sudo docker run \
  --log-driver=splunk \
  --log-opt tag="{{.Name}}" \
  --log-opt splunk-url=$HUMIO_URL \
  --log-opt splunk-token=$HUMIO_INGEST_TOKEN \
  --detach \
  --name nginx \
  --mount="type=volume,source=letsencrypt,destination=/etc/letsencrypt,readonly" \
  --net=dockernet \
  --publish=80:80/tcp \
  --publish=443:443/tcp \
  --restart=unless-stopped \
  --tty \
  nginx
