#Tags
#
#    latest : latest versions of rTorrent/libtorrent.
#    Use $RTORRENT_VER-$LIBTORRENT_VER to get specific versions of rTorrent/libtorrent.
FROM wonderfall/rtorrent-flood:0.9.7-0.13.7

EXPOSE 3000

# Set the default command
CMD ["/usr/bin/run.sh"]
