#!/bin/bash
source $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/../before_run

sudo docker run \
  --detach \
  --env TZ="$TZ" \
  --mount='type=volume,source=unifi,destination=/unifi' \
  --name=unifi \
  --net=host \
  --restart=unless-stopped \
  unifi