#!/bin/sh
# Render a committed rathole config with environment-backed secrets.
set -eu

TEMPLATE="${RATHOLE_CONFIG_TEMPLATE:?set RATHOLE_CONFIG_TEMPLATE}"
RENDERED=/run/rathole.toml

envsubst '${RATHOLE_TOKEN} ${RATHOLE_NOISE_LOCAL_PRIVATE_KEY} ${RATHOLE_NOISE_REMOTE_PUBLIC_KEY} ${RATHOLE_PUBLIC_TLS_TOKEN} ${RATHOLE_FORGEJO_SSH_TOKEN} ${RATHOLE_PROTECTED_HTTP_TOKEN} ${RATHOLE_BILBY_SSH_TOKEN} ${RATHOLE_VOLTAIRE_SSH_TOKEN} ${RATHOLE_KANGAROO_SSH_TOKEN} ${RATHOLE_FRACTAL_SSH_TOKEN} ${RATHOLE_FRACTAL_HTTP_TOKEN} ${NUMBAT_APPLICATION_IPV4} ${NUMBAT_RELAY_IPV4}' \
  < "$TEMPLATE" > "$RENDERED"

exec rathole "$RENDERED"
